version: '3.3'

services:
  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    env_file: ./.env  # Arquivo de variáveis de ambiente
    networks:
      - leantime-net
    volumes:
      - public_userfiles:/var/www/html/public/userfiles  # Volume para arquivos públicos (logo, etc.)
      - userfiles:/var/www/html/userfiles                # Volume para arquivos privados enviados pelos usuários
      - plugins:/var/www/html/app/Plugins                # Volume para plugins (descomente se for usar plugins)
    ports:
      - "${LEAN_PORT}:80"  # Porta exposta para acessar o Leantime
    # Remova o depends_on, já que não há mais um banco de dados interno
    # depends_on:
    #   - leantime_db

volumes:
  userfiles:
  public_userfiles:
  plugins:

networks:
  leantime-net: